# by akashmaji
"""
Day-14.ipynb

Automatically generated by Colaboratory.

Original file is located at:
    https://colab.research.google.com/drive/1aF2BdWu3rWnfxOCebEtWAA9g3BoWvza_
    
"""

# .ipynb => iron python notebook

# decimal -> binary

# 12   => 1100

# 10 =>   1010
# 8 =>   1000

# 8   8/2   0
# 4   4/2   0
# 2   2/2   0
# 1   1/2   1
# 0    (stop)

n = 100
ls = []
while n != 0:
    if n % 2 == 0:
        ls.append(0)
    else:
        ls.append(1)
    n = n//2 #integer  9//2   4  (not 4.5)

for i in ls[::-1]:
    print(i, end = " ")


# string = "akash"
# print(string[::-1])


# string[::-1]     #complete string in reverse

# anagram

#  abcc  -> cbac
# yes

# defd => dedg
# no

# racecar
# r 0
# a 0
# c 0
# e 0

# acercar

# dictionary

string1 = "aeiou"
string2 = "aeiok"

map = {}
for ch in string1:
    if ch in map:
        map[ch] += 1
    else:
        map[ch] = 1
print(map)



for ch in string2:
    if ch in map:
        map[ch] -= 1


# kya map me sare values 0 hain ?
anagram = True

for key in map:
    if map[key] != 0:
        anagram = False
        break
    
print(map)
print(anagram)

def heron(n, e = 0.0001):
   
    prev = 0
    curr = n

    while True:

        prev = curr
        curr = (curr + n/curr) * 0.5
    

        if abs(prev - curr) <= e:
            print(prev, ans)
            break

    return prev

n = 25
ans = heron(n)
print("Square root of {0} is {1:0.2f}".format(n, ans))
