# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atCn7kwvS6tUmf9TyycWW1-7X8xXiYnF
"""

# empty class

class Pen:
    # yha pe kuch nhi hoga
    # empty class
    pass

mypen = Pen()
print(mypen)

# id => 0x7f019e420210 (memory adress)

print(id(mypen))  # id() => identity => get mme the address

# baad me dekh lenge
print(139644926736464 == 0x7f019e420210)

class Student:
    # constructor
    def __init__(self):
        # attributes
        self.name = "Akash"
        self.age = 30

obj = Student()
print(obj.name)
obj.name = "Akaash"
print(obj.age)
obj.age = obj.age + 1

print(obj.name)
print(obj.age)